### ISSUE TITLE
Payment Methods Component

### ISSUE THREAD

**Issue by gvc** [vtex/faststore#1040]
I'm creating this issue to let chime in if this should be an atom/molecule or organism and if it should be implemented on faststore or on base.store.

The Payment Methods is a list of accepted payment methods a store has. 

[Figma link](https://www.figma.com/file/zHMOtOPduiM0hNNcg21iR1/Handoff-PDP-v0.1?node-id=240%3A62339) | [Pull Request](https://github.com/vtex/faststore/pull/1024)

**Comment by emersonlaurentino** [comment]
I think this component should be in the store. Because he's a simple `div`, but keep in the faststore if the flag prop is an array of strings and the user can choice what the flags should display instead of importing the flag icon.

**Comment by emersonlaurentino** [comment]
> About what @emersonlaurentino said, I think the idea is that the developer should be able put anything as "flags": an icon, a string, a link....

But we want the user to put anything? because the use case we need is only the image/icon, so we can give that.

**Comment by saranicoly** [comment]
> > About what @emersonlaurentino said, I think the idea is that the developer should be able put anything as "flags": an icon, a string, a link....
> 
> But we want the user to put anything? because the use case we need is only the image/icon, so we can give that.

The use case is only image/icon, but if the developer wants to use it another way, I don't see why we shouldn't allow it. What do you think?

Anyway, It's a simple component, if most of us agrees it should be in base store, I'm ok with that too.

**Comment by hellofanny** [comment]
closing because we decided to classify it as `molecule` https://github.com/vtex/faststore/pull/1024
