### ISSUE TITLE
Banner component

### ISSUE THREAD

**Issue by gvc** [vtex/faststore#1042]
I'm creating this issue to let chime in if this should be an atom/molecule or organism and if it should be implemented on faststore or on base.store.

The Banner component is a content driven component that displays some text and an image. 

[Figma link](https://www.figma.com/file/zHMOtOPduiM0hNNcg21iR1/Handoff-PDP-v0.1?node-id=572%3A57357)

**Comment by emersonlaurentino** [comment]
Yes, this should be done on faststore as an organism

**Comment by hellofanny** [comment]
After few discussion we decided to classify it as molecule https://github.com/vtex/faststore/pull/1048, but I still think it suits better as an organism.

**Comment by emersonlaurentino** [comment]
closing because https://github.com/vtex/faststore/pull/1048 was merged
