### ISSUE TITLE
Newsletter component

### ISSUE THREAD

**Issue by gvc** [vtex/faststore#1043]
I'm creating this issue to let chime in if this should be an atom/molecule or organism and if it should be implemented on faststore or on base.store.

The Newsletter component represents the form that is shown to the user as a way to collect user e-mails and send them information about the store.

[Figma link](https://www.figma.com/file/zHMOtOPduiM0hNNcg21iR1/Handoff-PDP-v0.1?node-id=36%3A41903)

**Comment by emersonlaurentino** [comment]
This should be done on faststore as an organism
