### ISSUE TITLE
Incentives/Highlight Component

### ISSUE THREAD

**Issue by gvc** [vtex/faststore#1045]
I'm creating this issue to let chime in if this should be an atom/molecule or organism and if it should be implemented on faststore or on base.store.

The Incentives/Highlight component is a showcase of highlighted traits either of the store or of the product.

[Figma link](https://www.figma.com/file/zHMOtOPduiM0hNNcg21iR1/Handoff-PDP-v0.1?node-id=230%3A46998) | [PR](https://github.com/vtex/faststore/pull/1031)

**Comment by tlgimenes** [comment]
I think we can code this on fatststore, however it would only be a div that renders children ... I feel we need an icon pack theme on faststore so we can have these icons first hand and actually give something to our store developers.

**Comment by emersonlaurentino** [comment]
Yes, this should be done on faststore as an atom

**Comment by lucasfp13** [comment]
I created another PR regard the `Incentive` atom implementation, please take a look at #1064.

**Comment by hellofanny** [comment]
As mentioned above, we decided to classify it as `atom` on faststore. https://github.com/vtex/faststore/pull/1064
