### ISSUE TITLE
Slug pagination is maintained when changing department/category

### ISSUE THREAD

**Issue by GuilhermeMacedo21** [vtex/faststore#1810]
**Describe the bug**

When we are on a department / category page specified by query or url, example:
https://nextjs.vtex.app/kitchen---home-appliances?page=5 
And we change to another page using react's Link component, this pagination is maintained by the search context

**Expected behavior**

When the user is on a department page and switches to another department, pagination should start from 0

**Current behavior**

From what I've verified, this pagination is being saved by the context of useSearch(), since, as it is a dynamic page, it considers that it is still in the same search.

**Steps to reproduce**

A step-by-step on how to reproduce the bug behavior.

1. Acess any page from department/category, like: https://nextjs.vtex.app/kitchen---home-appliances?page=5
Obs: Have to be in a specific page because infinite scroll pushes all previus pages
2. Click in another department/category
3. The pagination will continue from the same as it was in the other department

GIF showing the bug: https://ibb.co/pW9kH83

**Possible Solution**

A possible solution is to check if the page slug has changed and reset the pagination

**Workspace**

Not necessary, because this happens in https://nextjs.vtex.app/

**Comment by icazevedo** [comment]
Fixed with #2043 and #2045.
