### ISSUE TITLE
Feedback for “Creating a new section”

### ISSUE THREAD

**Issue by vivaltech** [vtex/faststore#1875]
Hi team! 

I've made the changes and ran `yarn cms-sync` command, but I can only see the published sections/contents. 

Is there any way to see the ones in drafts? If not, I think we can clarify that here in the docs.

Thank you in advance!

**Comment by hellofanny** [comment]
Hi @vivaltech! Thanks for leaving a feedback here!
Sorry! The doc was outdated, we are working to keep everything up-to-date 🙏 
I believe you were trying to sync your new sections/contents to the cms, the correct command should be `faststore cms-sync`.

We've update the docs. Can you please try again following this [guide](https://www.faststore.dev/docs/building-sections/creating-a-new-section)?

Lemme know if it works! 😃
