### ISSUE TITLE
Uma nova versão do IO ?

### ISSUE THREAD

**Issue by Yokaito** [vtex/faststore#1887]
**What are you trying to accomplish? Please describe.**
A clear and concise description of what is your question and what you're trying to accomplish.

Gostaria de entender ou alguma explicação, da mudança de objetivo com a FastStore. Tivemos uma implementação feita com a versão "antiga" na qual tínhamos acesso completo a componentes,hooks e todo o layout da loja.

Agora temos uma seção de overrides na qual apenas o lugares permitidos serão alteráveis. Eu entendo o problema de a vtex ter mais controle da loja que esta sendo feito deploy. Mas sair de algo totalmente customizavel para algo onde apenas os lugares permitidos? Como ficam os outros pontos?

- Integrações terceiras, utilizando ServerSideProps, StaticProps, StaticPaths ?
- Poder alterar a implementação de scss para outra ?
- Como não utilizar o override e ter controle do layout completo da loja.

**What have you tried so far?**
A clear and concise description of what you tried to do already.

Seguindo a própria documentação eu posso criar nos componentes, novas seções e dar um override num componente já existente até aí ok. Mas e se eu quiser trocar o ProductDetails todo? Eu tenho que conviver com a estrutura que está la e adaptar e não criar uma da zero como eu poderia antes.

**Additional context**
Add any other context or comment about your question.

![maxresdefault](https://github.com/vtex/faststore/assets/20995335/2beb379c-9199-4795-8fed-bf63d91443cb)

**Comment by vmlira2** [comment]
Olá, @Yokaito! Ficamos felizes em ver que você está testando nossas atualizações. De fato, agora temos um formato novo de customização para poder entregar as equipes de desenvolvimento uma estrutura com fácil atualização e para isso precisamos criar algumas restrições.

_Integrações terceiras, utilizando ServerSideProps, StaticProps, StaticPaths?_

- Tomamos a decisão de limitar a edição dessas integrações, por enquanto. Vimos que diversos usuários acabaram não seguindo boas práticas do Next e tiveram a performance da loja prejudicada.

- Faz parte da nossa visão permitir essas integrações, mas estamos definindo as melhores abordagens para isso, pois queremos reduzir utilizações que prejudiquem a performance.

_Poder alterar a implementação de scss para outra?_

- Hoje não é possível usar outros frameworks nos nossos componentes nativos, mas você pode usar qualquer framework nos seus componentes customizados.

- Estamos estudando a possibilidade de se retirar todos os nossos estilos padrões e deixar apenas os data-attributes para a equipe de desenvolvimento usar o que preferir.

_Como não utilizar o override e ter controle do layout completo da loja._

- Através do CMS, você tem o controle completo do que vai aparecer na loja, então é possível retirar os componentes nativos e adicionar apenas as versões customizadas

- Adoraríamos entender melhor o que você está tentando fazer. Se puder compartilhar mais informações, é possível que tenhamos sugestões específicas ou podemos levar sua necessidade para nosso time de produto.

_Mas e se eu quiser trocar o ProductDetails todo?_

- Você pode criar uma [seção nova](https://www.faststore.dev/docs/building-sections/creating-a-new-section), remover ProductDetails lá da Product Details Page do CMS e adicionar a nova seção que você criou. Para construir essa seção você ainda pode usar os [nossos componentes da biblioteca](https://www.faststore.dev/components) e criar as integrações necessárias.

**Comment by vmlira2** [comment]
Ah, só um adendo: Você mantém o mesmo poder da versão anterior. O pacote core é a loja completa. Ao clonar e rodar o repositório localmente, não é necessário fazer overrides ou seguir nossas convenções. O repositório starter é uma versão enxuta com uma API opinionada. O repositório da FastStore continua igual, mas agora com a possibilidade de seguir o padrão de overrides definido pela VTEX.

Nosso objetivo é garantir uma melhor mantenabilidade das lojas, porém é possível desviar da compatibilidade proposta pela VTEX e seguir com uma implementação Headless e alterar os arquivos diretamente no projeto Next.js. 

A consequência disso é perder algumas vantagens proporcionadas pela VTEX, como a capacidade de se beneficiar com novos componentes, integrações, bug fixes, melhorias de segurança ou performance, por exemplo. Além disso, também perde-se a capacidade de plugar na nossa camada de infraestrutura, que resolve questões de hosting, CI/CD, disponibiliza métricas de cloud, etc. 

Ou seja, há um caminho fora das convenções propostas. Neste caminho o usuário ganha liberdade/controle, porém perde vantagens de mantenabilidade e está sujeito a mais riscos de reduzir a performance da loja.
