### ISSUE TITLE
Support custom Cypress tests in CI/CD

### ISSUE THREAD

**Issue by erinmorrissey-hearst** [vtex/faststore#1888]
**What are you trying to accomplish? Please describe.**
We'd like to be able to add our own Cypress tests to our FastStore projects. There's no barrier to us doing that, but the tests do not get pulled into the CI/CD test run. 

**What have you tried so far?**
Based on some local testing, a change to the `faststore` Cypress config file (see line 9 below) pulls in our custom tests along with the existing FastStore tests when running the tests from the `.faststore` directory. My assumption is that this small change might mean the tests would also get automatically pulled into the CI/CD test run?

There might be a better way to do this, and the interface in the Cypress app becomes admittedly a little clunky with all those nested folders.

Would you consider this change, or do you already have plans to support including customer Cypress tests in CI/CD?

**Additional question**
Also wondering if you have plans to upgrade to the latest Cypress version (v12)?

<img width="533" alt="config for v9 - in faststore" src="https://github.com/vtex/faststore/assets/130610878/122fb6d4-a1a0-4fcf-a1c6-be568e6f8dba">

<img width="707" alt="joint - app interface" src="https://github.com/vtex/faststore/assets/130610878/ac3a6e15-881a-495c-91ed-d506eb3f1b8b">

**Comment by erinmorrissey-hearst** [comment]
Adding a follow-up question to ask about the overall plan for E2E testing in FastStore — the existing Cypress tests in FastStore are currently [broken](https://github.com/vtex-sites/demohearst.store/pull/18/checks?check_run_id=15058724351) in our demo repo (ex: Some analytics tests assert a certain number of products are visible, but our catalog setup means that assertion is false). This approach where tests are dependent on catalog setup, and where the customer can supposedly completely customize their storefront without the ability to change the tests, doesn't seem ideal.

Should we expect changes to the E2E testing approach in FastStore?

We'd also like to get the issue with the breaking tests resolved in the meantime so we can get back to a passing build state in our FastStore demo instance, and to make sure our QA instance doesn't end up with the same problem.

**Comment by gvc** [comment]
Regarding the update of Cypress, it has not yet been prioritized by our team but we've taken note 📓.

**Comment by erinmorrissey-hearst** [comment]
@gvc Thanks for the new `enableCypressExtension` flag! I have been testing it out and it does seem to give us a path forward for including our own custom tests, but I wanted to share a little initial feedback on a few issues I've encountered:
1. The new [docs](https://www.faststore.dev/docs/faststore-config-options/custom-cypress-test#step-2-integrating-custom-cypress-tests-into-your-faststore-project) suggest test files should be located in `cypress`, but to run those tests locally, I need to add `"integrationFolder": "cypress"` to the Cypress config file since the `cypress open` command looks for tests in `cypress/integration` by default. If locating tests in just `cypress` will remain the convention, I think that workaround should be documented as any user will want to run tests locally first.
2. In our custom test files, I haven't found a way to import from the Faststore config file (to use the page URLs stored there) that works both locally and in CI. We can work around this by storing URLs locally in the file, but a user who looks at the OOTB tests for examples may see your pattern of importing from the config file and run into the same problem.

<img width="992" alt="Screenshot 2023-08-15 at 11 02 57 AM" src="https://github.com/vtex/faststore/assets/130610878/2fa755b3-ee3c-49df-be6d-2f11084eea1e">
<img width="913" alt="Screenshot 2023-08-15 at 2 54 26 PM" src="https://github.com/vtex/faststore/assets/130610878/0b7989bd-1dce-4cd8-ad61-f458de45c6eb">
<img width="838" alt="Screenshot 2023-08-15 at 3 31 19 PM" src="https://github.com/vtex/faststore/assets/130610878/f8d0dac9-eff2-4b51-a7f8-40d6f99e62a5">


3. Since the existing issue where the OOTB Faststore Cypress tests are currently failing for us due to catalog differences, we now have to add empty/dummy test files to overwrite the OOTB tests and get to a passing test run, which doesn't seem like a very clean pattern. Have you considered a fix where we can turn off all of the OOTB tests with another flag or config change instead?

**Comment by hellofanny** [comment]
Thank you so much for leaving this initial thoughts about this experimental feature 🤩  

1. I think we should keep the default `cypress/integration`. We'll change it. 
2. 🤔 We'll take a look into this issue
3.  The inclusion of a disabled configuration is currently not in our plans. We'll prioritize improving our OOTB tests, refining and making the tests more versatile to avoid this problem.

Please don't hesitate to share additional feedback as you explore this feature. It will help us to improve it. 🚀 🚀 🚀

**Comment by lucasfp13** [comment]
Hey @erinmorrissey-hearst 👋🏼 
First of all, thank you for the feedback, it was very important for us think and discuss deeply about these Cypress-related improvements.

Regarding your points, we improved our documentation in #2080 to inform the correct location where custom tests should be, the `cypress/integration` folder. We also have the #2092 with more documentation improvement being reviewed and merged soon to give you a way to exclusive execution of your custom tests (ignoring the OOTB tests), but you will only be able to do this with Cypress 12.

FastStore already has the feature flag to enable Cypress 12, you can enable this in your `faststore.config` file inside the `experimental` section by adding the `cypressVersion: 12`. After that, you can follow the [official Cypress guide](https://docs.cypress.io/guides/references/configuration) to replace your `cypress.json` with the new `cypress.config.ts` file. We did the same for our Starter store [here](https://github.com/vtex-sites/starter.store/blob/main/cypress.config.ts).

Then, just rename the folder where all of your custom tests are from `cypress/integration` to `cypress/e2e`, the **Integration tests** check will run only for your custom tests.

If you have any other questions, don't hesitate to answer here, we will wait for your feedback 😉

**Comment by erinmorrissey-hearst** [comment]
Thanks @lucasfp13! We did upgrade to Cypress v12 a few weeks back and just pushed some changes to successfully bypass the OOTB Faststore integration tests using the folder rename approach.
