### ISSUE TITLE
Erro ao instalar o plugin cms

### ISSUE THREAD

**Issue by agliardiDigital** [vtex/faststore#1889]
Estou num projeto faststore onde estamos com o desenvolvimento avançado.

Nesse meio tempo troque de um macbook air 2015 para um mackbook pro m2, nesse macbook novo eu fui configurar o ambiente e o build, develop tudo funcionou certinho, porém, quando fui dar um sync para sincronizar com o Headless CMS deu erro pois o plugin não estava instalado.

Após isso eu tentei de todas as formas seja via brew ou npm instalar o plugin porém fica dando o mesmo erro.
<img width="1001" alt="Captura de Tela 2023-07-17 às 13 27 22" src="https://github.com/vtex/faststore/assets/138252022/57b1aa87-50cd-4c74-86f0-8e6e9361e1ce">
<img width="812" alt="Captura de Tela 2023-07-17 às 14 45 11" src="https://github.com/vtex/faststore/assets/138252022/540da73b-19b3-4d17-a59c-eb2aa298fc75">

**Comment by eduardoformiga** [comment]
Olá, @agliardiDigital tudo bem?
Temos alguns erros mencionados. No caso da versão do node, ela precisa ser uma versão maior que a 15, consegues atualizar e tentar novamente?
[Aqui está a nossa documentação](https://www.faststore.dev/docs/getting-started/2-setting-up-the-project#before-you-start) que explica isso :)

**Comment by beatrizmaselli** [comment]
Opa, @agliardiDigital ! Tudo certinho?
Também troquei para o chip m2 e tive o mesmo problema! Por aqui usei o comando `yarn config set ignore-engines true` para ignorar incompatibilidades da versão do node ao instalar o pluggin e funcionou certinho :) 
Acho que vale testar se resolve o seu caso também!
