### ISSUE TITLE
UI is not rendering the HTML description Properly 

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#1893]
**Describe the bug**
UI is not rendering the HTML description of the product properly

**Steps to reproduce**
Go to any PDP page

**Screenshot**
![Screenshot 2023-07-18 at 1 01 31 PM](https://github.com/vtex/faststore/assets/137450920/207c27de-d4a6-4b7e-98d2-f0e03660f52f)

#evergreen
"@faststore/core": "2.1.43",

**Comment by hellofanny** [comment]
Thanks for reporting!
How are you passing this description data to this component?

**Comment by victors-hearst** [comment]
the descriptions are coming from the CMS

```
<p><span style="color: rgb(0,0,0);background-color: rgb(255,255,255);font-size: 16px;font-family: Work Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;">Our Rest Day shirt is the perfect long sleeve tee that is incredibly soft with great drape, stretch, and recovery with a vintage look.</span></p>
```

![Screenshot 2023-07-18 at 1 43 12 PM](https://github.com/vtex/faststore/assets/137450920/bcdfcb10-fee6-41e6-872b-7c807eeb8835)

This is how it looks old version of Strorefront

![Screenshot 2023-07-18 at 1 45 13 PM](https://github.com/vtex/faststore/assets/137450920/94624905-19eb-4897-b6db-5dbc3f800a68)

**Comment by icazevedo** [comment]
#2050 fixed this!
