### ISSUE TITLE
Image Gallery is not centering the product and cannot zoom in

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#1894]
**Describe the bug**
Image Gallery is not centering the product and cannot zoom in

**Steps to reproduce**
Go to any PDP page [example](https://demohearst.vtex.app/cassandra-monogram-sandals-4545535-454684/p)

**Screenshot**
<img width="1337" alt="Screenshot 2023-07-17 at 11 53 40 AM" src="https://github.com/vtex/faststore/assets/137450920/ef9fb20d-bbe4-444d-ba06-3c060e359d94">

#evergreen
"@faststore/core": "2.1.43",

**Comment by hellofanny** [comment]
Hi @victors1682 👋 

1. Related to the zoom in feature, it's not implemented yet 🙇‍♀️ . The component's name may have caused this confusion, and we should rename it. We will work on it.

2. Not sure why the Image is not centering. I've tried this image link here, and it seems to be cropped as expected. Have you changed any prop when calling it?
![image](https://github.com/vtex/faststore/assets/3356699/19629598-de89-4a17-9e12-5f7e33912a03)

**Comment by victors1682** [comment]
@hellofanny Hello, I think is because the old storeFront has the image property `object-fit: contain` while the faststore use `object-fit: cover;` 

### storeFront

<img width="803" alt="Screenshot 2023-07-24 at 3 27 04 PM" src="https://github.com/vtex/faststore/assets/137450920/f7adc60b-3aa9-40dc-9511-6c8279855afb">

A workaround might be to add another property  `object-position: bottom;` to center all the images using cover.


<img width="1808" alt="Screenshot 2023-07-24 at 3 39 38 PM" src="https://github.com/vtex/faststore/assets/137450920/70c49b3c-3af6-4433-926e-b369e7b5bfe3">

### Enabled

<img width="1891" alt="Screenshot 2023-07-24 at 3 40 10 PM" src="https://github.com/vtex/faststore/assets/137450920/fa050302-a6b4-40f9-8904-2626b283e4a9">

**Comment by hellofanny** [comment]
Hey @victors1682 👋  I've got some updates! 

➡️ We've added a new prop to help position the image in the [ImageGallery](https://www.faststore.dev/components/organisms/image-gallery#image-gallery). You can try using the `imagePosition` prop for it.
➡️ The `imagePosition` can also be set via CMS
⚠️ We've renamed the `ImageZoom` component. Now it's called `ImageGalleryViewer`. The image's zoom feature will be implemented in the future.

These changes are available on `@faststore/core": "2.1.93`

**Comment by victors1682** [comment]
@hellofanny  thank you! I'll try this out!
