### ISSUE TITLE
Upgrade FastStore Node version

### ISSUE THREAD

**Issue by hahnwhitney** [vtex/faststore#1896]
**Describe the feature you'd like**
There are currently multiple versions of Node running in different parts of our pipeline; we should standardize and use one single version for each step. Having a consistent Node version for every step in the pipeline will make things more predictable and ensure that the app operates in the same environment. Upgrading will also give us access to the latest tools and ensure that we can access security updates and bug fixes.

Node 18 is the active "LTS" (long-term-support) version and is likely the best choice. It is recommended for most users and contains new features, bug fixes, and updates.

**Describe alternatives you've considered**
Instead of upgrading directly to Node 18, we could upgrade from 14 to 16 and then to 18, but that is likely more trouble and more time-consuming than jumping directly to Node 18.

**Additional context**
It appears that there are multiple versions of Node running in different parts of VTEX Sites pipeline:

- `build` step uses Node `14.19.3`
- `SonarQube` step uses Node 10
- `Integration Tests` (Cypress) step uses Node `16.14.2`

- Node 10 reached EOL (end-of-life) in October 2016
- Node 16 reached EOL in April 2023
- Node 18 is currently the LTS (long-term-support), and will enter “maintenance” mode in October 2023

**References**
[Node.js Release Schedule](https://github.com/nodejs/Release/tree/main#nodejs-release-working-group)

**Comment by hahnwhitney** [comment]
There are several places the Node version needs to be changed. Some of these upgrades are more valuable than others.

- **.codesandbox/ci.json**
  - change `"node": "16"` to `"node": "18"`
- **.github/workflows/ci.yml** and **.github/workflows/release.yml**
  - change `"node-version": "16"` to `"node-version": "18"`
- **package.json**, **packages/cli/package.json**, and **packages/components/package.json **
  - change `volta` object from `"node": "16.18.0"` to `"node": "18.16.1"`
- **packages/core/package.json**, **packages/lighthouse/package.json**, and **packages/sdk/package.json**
  - change `engines` object from `"node": ">=10"` to `"node": ">=18"`
- **packages/ui/package.json**
  - change `engines` object from `"node": ">=10"` to `"node": ">=18"` and change `volta` object from `"node": "16.18.0"` to `"node": "18.16.1"`

**Comment by hahnwhitney** [comment]
Ok, in that case, I think it makes sense to prioritize the Node 16 upgrades like this:

1. packages/core/package.json
2. packages/sdk/package.json
3. packages/ui/package.json
4. packages/lighthouse/package.json

**Comment by icazevedo** [comment]
This is now supported through the experimental feature flag `nodeVersion: 18` on `faststore.config.js`.

```js
...
experimental: {
  nodeVersion: 18,
},
...
```

To create initial cache on `nodeVersion` 18, disable these variables on `vtex.env` on the first build that uses this version:
```env
USE_BUILD_CACHE=false
USE_NODE_MODULES_CACHE=false
USE_FRAMEWORK_CACHE=false
```
