### ISSUE TITLE
Nested <footer> elements in FastStore v2

### ISSUE THREAD

**Issue by batzlerg** [vtex/faststore#1901]
**Describe the bug**
The [`Footer` section](https://github.com/vtex/faststore/blob/main/packages/core/src/components/sections/Footer/Footer.tsx#L51) and the [`Footer` UI element](https://github.com/vtex/faststore/blob/main/packages/core/src/components/common/Footer/Footer.tsx#L13) that it renders both use the `<footer>` tag, leading to nested footer elements.

**Expected behavior**
One `<footer>` element at the top level of the page

**Current behavior**
Nested `<footer>` elements on the FastStore v2 starter and any stores that don't override the relevant components

**Steps to reproduce**
Visit any FastStore Evergreen store ([e.g.](https://hearstqa.vtex.app/)) and inspect the footer to see the nested elements. This appears to be 

<img width="645" alt="Screen Shot 2023-07-19 at 10 44 09 AM" src="https://github.com/vtex/faststore/assets/5392478/381410ce-b719-47cb-86be-b40b81ef377b">

**Possible Solution**
Decide whether the section or the UI component should be responsible for rendering the footer and replace the other `<footer>` tag with a `<div>`

**Additional context**
This doesn't directly violate WCAG 2.1 guidelines but it can be [confusing for screen readers](https://dequeuniversity.com/rules/axe/4.7/landmark-unique?application=AxeChrome) and isn't a great practice from a semantic HTML perspective.

This appears to have been introduced in the v1 -> v2 transition, since the FastStore Classic / v1 starter renders the `Footer` UI component directly in `Layout`. [`vtexfaststore.com`](https://www.vtexfaststore.com/) seems to be running v1 since it does not have this issue.

**Comment by hellofanny** [comment]
Hey @batzlerg, thanks for reporting this issue and the detailed context !🌟 
We created an internal task to fix it soon.

**Comment by hellofanny** [comment]
[Done](https://github.com/vtex/faststore/pull/1950) 🚀
