### ISSUE TITLE
Undefined media query mixins in component SCSS

### ISSUE THREAD

**Issue by hahnwhitney** [vtex/faststore#1905]
**Describe the bug**
The `media(">=notebook")` and `media(">=tablet")` mixins are defined in `@faststore/ui/src/styles/base/utilities`; when we try to use these in the components, they are undefined.

**Expected behavior**
A component CSS file that uses a media query should  mixin defined in a separate file should include the code for that media query at the top of the component file (potentially with an `@import` or `@use`).

**Current behavior**
Component CSS files are currently missing a method to include/import for these mixins, resulting in them being undefined.

**Possible Solutions**
- Add `@import "./../../../styles/base";` at the top of the component file – this works because the mixin is defined in `base/utilities`, and is then imported into the base file.
- Simplify media queries code pattern 🤷‍♀️

**Comment by hahnwhitney** [comment]
Note: This was originally part of https://github.com/vtex/faststore/issues/1904 -- I created this issue because the solution for media query mixins is going to be different than the other mixins.

**Comment by renatamottam** [comment]
Thanks for the explanation, Whitney! We're going to propose an easier way to customize the breakpoints values and add it on the documentation soon ☺️

**Comment by renatamottam** [comment]
Hey Whitney, we have some updates related to this issue ✨ 

We created a new PR proposing an update on the `@faststore/ui` to add the possibility of override our `breakpoints` and other `@mixin` along with a [documentation page](https://faststore-site-git-feat-media-queries-fs-1207-faststore.vercel.app/docs/customizing/mixins-breakpoints) with all the steps needed. Feel free to test it and see if it makes sense to your project.

The PR link: #1917
