### ISSUE TITLE
PDP product specifications overflow the right panel

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#1910]
PDP product specifications overflow the right panel

<img width="1575" alt="Screenshot 2023-07-24 at 12 21 07 PM" src="https://github.com/vtex/faststore/assets/137450920/73b8b32f-ab69-44d3-9614-0f1fbc82a6b7">

**Comment by hellofanny** [comment]
Thanks, @victors1682, for reporting. We noticed this a few days ago 🙈 
We've created a task to fix it in the [SkuSelector](https://www.faststore.dev/components/molecules/sku-selector) stylesheet soon.

In the meantime, you can temporarily fix it by using the SkuSelector data-attr `[data-fs-sku-selector-list]`. Apply the code below in the theme file, following the instructions provided in this [guide](https://www.faststore.dev/docs/customizing/components).  I hope it helps. 🙃

```
[data-fs-sku-selector] [data-fs-sku-selector-list] { 
   flex-wrap: wrap;
   row-gap: var(--fs-spacing-1);
}
```

**Comment by victors1682** [comment]
@hellofanny that works! thanks feel free to keep the issue open or close it if you want to track this for the Core!
