### ISSUE TITLE
Display the right image of color variation on PLP

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#1911]
The user can search by Colors, Size, and other variations of the products, however when the UI is not showing the right image or there’s no indicator about the color being filtered.

Filter: Punch Black.

The following result is a product that contains the variation, Black, however, there’s no indication about this, one suggestion was to add a color variation of each Card for a better user experience.

<img width="1036" alt="Screenshot 2023-07-24 at 1 38 07 PM" src="https://github.com/vtex/faststore/assets/137450920/e5b1d9e8-0eb5-4843-8198-d78e67a5b458">
 

Using the menu we can have the same experience

<img width="855" alt="Screenshot 2023-07-24 at 1 28 16 PM" src="https://github.com/vtex/faststore/assets/137450920/cda789c4-0139-4438-bf20-e5011ef599f5">

<img width="1222" alt="Screenshot 2023-07-24 at 1 24 46 PM" src="https://github.com/vtex/faststore/assets/137450920/48acc506-b87b-4365-b694-d4229ffdf486">

**Comment by gvc** [comment]
Hi @victors1682, we investigated and this is not an issue with FastStore but the account configuration. Can you please talk with your account manager? 🙇

**Comment by Lucaspoladore** [comment]
Hey @victors1682, 

So, we investigated and the answer is: 

- Intelligent Search returns the item as it's in the catalog document on the database. This means that we will show the image of the first SKU, no matter what filters we are passing through. 
- What we can achieve is to split through the specifications [(guide reference)](https://help.vtex.com/pt/tracks/vtex-intelligent-search--19wrbB7nEQcmwzDPl1l4Cb/5uVxuWxTA8VvLX3G8UCcUE). 
- Using the configuration above, we can say that color should split SKUs into a PLP. This would mean that if i have a T-Shirt as product and "colors" is a SKU Specification that we choose to split, then the PLP would come with all SKUs variations as separate
