### ISSUE TITLE
Ability to load third party scripts in faststore

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#1934]
In the previous version  StoreFront allowed to include of a third-party script 

V1 Documentation.
https://v1.faststore.dev/how-to-guides/performance/handling-the-impact-of-third-party-scripts

This is not available in Faststore, we really need this feature to be able to install monitoring scripts before launching day.

**Comment by hellofanny** [comment]
Hi victor 👋 , we currently don't have a way to allow it, but we have plans to.

**Comment by hellofanny** [comment]
Hey, @victors1682! Thanks for contributing to this issue. 🌟 
The proposal made on https://github.com/vtex/faststore/pull/1980 is already merged and available on FS core package version `2.1.82`!  🚀 
We'll release documentation about it soon.

**Comment by hellofanny** [comment]
We added a guide doc: https://www.faststore.dev/docs/handling-third-party-scripts
