### ISSUE TITLE
React Context API to be able to access to all the sections props  from Override components

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#1944]
**Motivations**
We would like to be able to install a Custom Section into an Overwrite Component. 

Currently, we have a Custom Navigation with the product specifications that need to be installed in the Global Section.

The problem: 
After installing the new component new <section> is placed below the native `nav` in the Headless CMS is hard to keep the new Nav in the right place.

<img width="2026" alt="Screenshot 2023-08-09 at 10 50 13 AM" src="https://github.com/vtex/faststore/assets/137450920/d54a8daf-1d1d-4960-ba74-815937d3ea73">

**Approach 1:** 
- Overwrite the Native nav to remove this section.
- Install the custom section and use JS to keep the Nav in the right position due to the Nav moving dynamically and CSS can not keep the custom nav in the right place, also when the top banner component is present the position of the menu is different. 

Problem: This approach is not consistent across different browsers and has and needs unnecessary computations to keep track of the user scrolling. 

_Bugs:_ 
<img width="960" alt="Screenshot 2023-08-09 at 11 14 37 AM" src="https://github.com/vtex/faststore/assets/137450920/73607cac-729b-4da7-a75c-3de895ff7e6f">

**Approach 2:**
Use a React Portal to inject the new section into the right `nav` tag, this approach make the custom section to be in the right place, however, during the rendering process, it needs to use a query selector to reach the navigation tag, with make it slow mounting the nav component, the user first sees the page then after a few milliseconds can see the Nav being rendering, this happens on every page during the navigation.

**Approach 3:** 
Overwrite the nav component and install the Custom Section in the same component, which makes the rendering process perfect and more flexibility to install any customization. 

_**The problem:**_ 
During the Overwrite process, we only have the component props available and in order to achieve this we need to have access to the custom sections. 

### 

> RECOMMENDATIONS

We did some testing creating a Global Context API to be able to access any sections in the Core

Example

New Basic Context
![Screenshot 2023-08-09 at 10 37 47 AM](https://github.com/vtex/faststore/assets/137450920/d240a7e7-e22e-4c6d-836d-2a102eed6d56)

Installing the provider

<img width="550" alt="Screenshot 2023-08-09 at 11 37 52 AM" src="https://github.com/vtex/faststore/assets/137450920/f293be62-6cfa-42bf-9385-e8cd0c5b936f">

**Overrite NavbarLinks**

```
import React from 'react';
import { useGlobal } from '../../../../GlobalContext';
import CustomNavigation from '../../sections/CustomNavigation/CustomNavigation';

export default function NavbarLinks() {
  const { sections } = useGlobal();
  const customProps = sections.find(section => section.name === 'CustomNavigation');

  if (customProps) {
    const { data } = customProps;
    return <CustomNavigation {...data} />;
  }

  return null;
}
```

Having access to the custom sections props also will give a lot of flexibility for any sections. 

<img width="677" alt="Screenshot 2023-08-09 at 11 57 41 AM" src="https://github.com/vtex/faststore/assets/137450920/7bd1c987-ec58-426e-a000-d4b774140e72">

PS: nice to have, the custom hook instead `useGlobal` to `useSection` can handle the logic to reach any sections

```
const mySection  = useSection('--Section Name--')
```

**Comment by icazevedo** [comment]
We're going to solve this problem with another approach coming soon. Thanks for the issue. This matter was discussed via Slack.
