### ISSUE TITLE
Typo in `Sku Selector` docs

### ISSUE THREAD

**Issue by hahnwhitney** [vtex/faststore#1945]
**Documentation description**
There is a typo in the `SkuOptions` section of the `Sku Selector` docs:

<img width="896" alt="Screenshot 2023-08-09 at 9 24 26 AM" src="https://github.com/vtex/faststore/assets/88338049/2a7c34d2-1c1b-4efe-a972-380b7c7361f1">

I believe the description for the `value` prop should say `Current value for this option.` instead of `Specifies that this option should be disabled.`

**References**
https://www.faststore.dev/components/molecules/sku-selector#skuoptions
https://github.com/vtex/faststore/blob/d6c0d6e8822194094100a40fbe58d4908451e819/packages/components/src/molecules/SkuSelector/SkuSelector.tsx#L28
https://github.com/vtex/faststore/blob/d6c0d6e8822194094100a40fbe58d4908451e819/apps/site/pages/components/molecules/sku-selector.mdx#L171

**Comment by hellofanny** [comment]
Hey @hahnwhitney
Thank you for reporting it! Well noticed! I'll be fixing it soon 🚀 🚀 🚀

**Comment by hellofanny** [comment]
[Here](https://www.faststore.dev/components/molecules/sku-selector#skuoptions) 😉
