### ISSUE TITLE
Setting hex color on skus in admin tool

### ISSUE THREAD

**Issue by arsaylor** [vtex/faststore#1953]
**What are you trying to accomplish? Please describe.**
I've been digging through the code and see that the variant 'image' | 'color' | 'label' is derived in this [file](https://github.com/vtex/faststore/blob/main/packages/components/src/molecules/SkuSelector/useDefineVariant.ts#L12) if there is not a specific [variant prop](https://github.com/vtex/faststore/blob/main/packages/components/src/molecules/SkuSelector/SkuSelector.tsx#L101) set on the SkuSelector. 

Based on the [sku options](https://www.faststore.dev/components/molecules/sku-selector#skuoptions) documentation, I should be able to set a hexColor on each sku. However, I cannot find a place in the admin product tool to set it.  Can someone show me in the admin tool where these hex values can be set at the sku level?

Since the SkuSelector component is nested a few layers down in the PDP, how would I go about specifically setting the variantProp mentioned above? Can that also be done somehow from the admin panel? Is it just in code? And if it is just in the code, can someone show me the best way to implement that?

**What have you tried so far?**
I've looked through the product and sku admin tools for anything labeled hex color and was unable to find anything. I even created a new sku specification called hexColor to see if that would work and it does not seem to.creating

**Comment by ArthurTriis1** [comment]
Hello arsaylor,

Thank you for your report, and I apologize for the delay in response. The hexColor feature in SkuSelector is intended for a new catalog feature that has not been implemented yet.

The FastStore team will promptly remove any reference to this option from the documentation to prevent confusion. In the meantime, we recommend using images in SkuSelector to represent the available color options. For example, we are using images refer to the [Apple mouse colors in the starter.store](https://starter.vtex.app/apple-magic-mouse-99988212/p).

To add an image as a SkuOption, simply upload a new image to a Sku in admin panel and set its label as "skuvariation." We are currently in the process of creating new documentation that will provide detailed instructions on how to do this.

Thank you for understanding, and feel free to reach out if you have any further questions or need assistance with it.
