### ISSUE TITLE
Extend the faststore.config.js information

### ISSUE THREAD

**Issue by vivaltech** [vtex/faststore#1966]
**What are you trying to accomplish? Please describe.**
Could we add a new property to the session in the faststore.config.js?

We would like to be able to enable a new property globally for the project and indicate the marketplaceName.

**What have you tried so far?**
It's possible, but we want to know if there's a better way to fetch this information.

**Additional context**
Currently in the product query from the pdp we have the seller identifier that corresponds to the seller name, but for the marketplace products the id comes as a number '1', and we would like to have a global variable available for all the custom sections to display the marketplace name.

**Comment by hellofanny** [comment]
Hey @vivaltech sorry for the delay! 
For this case, we think adding this new property in the `faststore.config.js` is better. It makes sense to have it as a global variable. 👍
