### ISSUE TITLE
Going back to a PLP from a PDP drops user at bottom of the page

### ISSUE THREAD

**Issue by erinmorrissey-hearst** [vtex/faststore#1972]
**Describe the bug**

If a user is on a PLP, clicks into a product, then from the PDP clicks the browser back button, the user is dropped at the very bottom of the PLP and sees the footer of the site (see video below).

https://github.com/vtex/faststore/assets/130610878/fbad1d18-9301-4e48-821c-503c669c31db

**Expected behavior**
After clicking the back button from the PDP, the user should see the product they just returned from roughly centered on the page. See the experience here for an example: https://www.patagonia.com/shop/web-specials

**Current behavior**
Not sure, I have not been able to find what code (if any) is causing this bug.

**Steps to reproduce**

1. Visit the "Office" category PLP on the starter store: https://starter.vtex.app/office
2. Click "Load more products" a couple times
3. Click into a product
4. Click the browser back button
5. Observe that you are brought back to the footer of the site instead of the previously clicked product

**Possible Solution**
Center the previously clicked product on the page (or at the very least, bring the user back to the top of the page rather than the bottom)

**Workspace**
n/a

**Additional context**
n/a

**Comment by hellofanny** [comment]
Thanks for reporting it! I've created an internal task to take a look into this bug.  🐞 🚀

**Comment by icazevedo** [comment]
Fixed on #2054
