### ISSUE TITLE
Native icons do not display in Firefox

### ISSUE THREAD

**Issue by vivaltech** [vtex/faststore#1973]
**Describe the bug**
I saw an unexpected behavior of the native icons in Firefox. If we open the documentation or the demo, they do not display.

**Expected behavior**
Show svg icons in Firefox.

**Current behavior**
Not being displayed.

**Steps to reproduce**
A step-by-step on how to reproduce the bug behavior.

1. Open a Firefox browser.
2. Go the documentation or demo environment. 
https://www.faststore.dev/components/atoms/icon
https://starter.vtex.app/
3. An empty space will be in the place where the icons are.

**Possible Solution**
I tried this solution from the Mozilla documentation: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use adding some properties by css but it didn't work.

**Workspace**
Add a workspace where you tested the bug behavior.

**Additional context**
Add any other context, screenshots, or comments about the problem.

![docs-firefox](https://github.com/vtex/faststore/assets/138598003/9e46e378-64d8-4d02-8aa4-977516be53e9)
![demo-mobile](https://github.com/vtex/faststore/assets/138598003/a295ba91-ce74-41b0-b45e-15452dbfb89a)
![demo-desktop](https://github.com/vtex/faststore/assets/138598003/b1db64a8-81de-492c-b148-ed42c40337ca)

**Comment by renatamottam** [comment]
Hey Victoria! Thanks for reporting this, I've already found the error, It was an opening and ending tag mismatch. I'll create a PR referencing this fix soon :)

**Comment by renatamottam** [comment]
We've lauched the FS package version `2.1.75` fixing the bug ✨
