### ISSUE TITLE
Variation selector issue

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#1977]
There's an issue with the variation selector:

1. When a variation is unavailable, it displays the "Notify when back in stock" component, after which the user cannot proceed with selecting additional variations. They need to use the back button.

2. If the default SKU is unavailable, the user loses the ability to select any other variations.
We're trying to handle this situation ourselves, but the StoreProduct doesn't have a property that tells us if a variation is not active.

![Aug-22-2023 18-07-22](https://github.com/vtex/faststore/assets/137450920/dd922e0b-c218-4061-892d-439a27335560)

Expected behavior: 
We want to disable unavailable variations

![image](https://github.com/vtex/faststore/assets/137450920/bfbed12c-e593-4fa2-ac09-678f10e697be)

We're trying to handle this custom component, however, StoreProduct doesn't have a property that tells us if a variation is not active.
![Screenshot 2023-08-23 at 11 10 02 AM](https://github.com/vtex/faststore/assets/137450920/39273abd-6d6e-4c2a-b639-edf6b82172a4)

**Comment by hellofanny** [comment]
Hey @victors1682, we decided to keep the Selector when the product is unavailable so the user can change to another SKU. The `Not Available` button is displayed when the SKU is unavailable.

🌟Changes available on  `@faststore/core: "2.1.99"`

**Comment by victors1682** [comment]
@hellofanny  nice! let me try this out! thank you
