### ISSUE TITLE
Github Actions Lighthouse output encoding issue

### ISSUE THREAD

**Issue by batzlerg** [vtex/faststore#1984]
**Describe the bug**
Github Actions Lighthouse output is difficult to parse because of characters that are not human friendly

**Expected behavior**
output should be formatted to exclude ANSI escape codes for terminal formatting, or they should be parsed into standard Unicode 

**Current behavior**
output does not do anything to ANSI codes, outputs gibberish

**Steps to reproduce**
1. run Lighthouse on FastStore CI/CD
2. view mangled output

**Possible Solution**
parse the ANSI codes or get rid of them

**Workspace**
N/A

**Additional context**
<img width="783" alt="Screen Shot 2023-08-28 at 5 12 33 PM" src="https://github.com/vtex/faststore/assets/5392478/73a44f5f-1d2b-47a0-b45d-cf6203259265">

Before:
```
�[31m✘�[0m �[1maria-required-parent�[0m failure for �[1mminScore�[0m assertion
```

After:
```
✘ maria-required-parent failure for minScore assertion
```

**Comment by hellofanny** [comment]
Closing because is already fixed ✅
