### ISSUE TITLE
Minicart - Prices for products kg/grams

### ISSUE THREAD

**Issue by carollaginestrac4** [vtex/faststore#1985]
**Describe the bug**

The issue arises when trying to display prices for products with variable weights (kg or grams) in the mini cart. The correct pricing information is missing from the display.

**Expected behavior**
The expected behavior is that prices for products with variable weights should be accurately displayed in the mini cart.

**Current behavior**
Currently, the mini cart does not correctly show the prices for products that have variable weights, causing inaccurate pricing information to be displayed.

**Steps to reproduce**
To reproduce the bug, follow these steps:

1. Add products with variable weights (kg or grams) to the cart.
2. Open the mini cart and observe the displayed prices.

**Possible Solution**
One possible solution could be to incorporate a field specifically for products with variable weights, allowing the correct pricing information to be displayed in the mini cart.
UnitMultiplier, measurementUnit and listPrice.

**Comment by beatrizmaselli** [comment]
Hello, Carolla! How are you?

Checking here the issue reported looks to me that is associated to the round of the price. 

Price at the miniCart: 15,34  Real Price: 15,33
<img width="1103" alt="image" src="https://github.com/vtex/faststore/assets/67066494/ce1997ad-b37c-4a9e-8ec2-e6eaf0b2ed13">

Checking the sellingPrice for this product at the simulation:
<img width="1046" alt="image" src="https://github.com/vtex/faststore/assets/67066494/825cbb8c-f77b-4a5c-ad24-d5898116b52f">

So the real price for this product is 15,33

Checking the price returned by the ValidateCartMutation:
<img width="489" alt="image" src="https://github.com/vtex/faststore/assets/67066494/55cd354c-904b-435d-8bcc-057b3c2c8a59">

The price stored is the real price of 15,33

Checking the price returned from the IS:
<img width="566" alt="image" src="https://github.com/vtex/faststore/assets/67066494/5c4688f4-949c-43b7-b907-c57d0a7e065f">

We have a price of 16.98 that if we multiply by the unit multiplier of 0.55 it will give us 9,339

This number should be truncated and not rounded as stated in this PR:
https://github.com/vtex-apps/store-graphql/pull/649

To format the number something like that should work:
const price = 9.339
const truncatedPrice =String(price*100).split(".")[0]/100 // 9.33

Hope this helps!

**Comment by carollaginestrac4** [comment]
1. There are issues with incorrect total and subtotal values (UseCart) when a weighable product is present in the cart, especially when the weighable product has a promotional price.

2. The list price represents the price per kilogram (kg), but the 'unitMultiplier' field is missing for the useCart.

3. Fetching the orderform slows down the minicart's performance.

4. Prices are inconsistent between the checkout and the orderform.

5. How are prices rounded? What's the rule? Is it based on the last two digits? Is rounding up or down applied? Could you clarify how the subtotal/total calculations are affected?

6. Occasionally, the 'validateCartMutation' throws a 500 error, causing it to stop being called and thus freezing the cart. Is there any error handling in place? To recover from this error, currently, it's resolved by either proceeding to the checkout and clearing the cart or by navigating to 'Application' > 'IndexedDB' and performing a full reset. This issue seems to be intermittent.

In the screenshot provided below, the first item is from 'useProduct,' and the second one is from 'useCart.'
![Screenshot_2023-08-31_at_10 40 42](https://github.com/vtex/faststore/assets/102303809/e9925edb-2c81-41bd-ba6a-b6f2fe1476f2)

**Comment by carollaginestrac4** [comment]
1. There are issues with incorrect total and subtotal values (UseCart) when a weighable product is present in the cart, especially when the weighable product has a promotional price.

2. The list price represents the price per kilogram (kg), but the 'unitMultiplier' field is missing for the useCart.

3. Fetching the orderform slows down the minicart's performance.

4. Prices are inconsistent between the checkout and the orderform.

5. How are prices rounded? What's the rule? Is it based on the last two digits? Is rounding up or down applied? Could you clarify how the subtotal/total calculations are affected?

6. Occasionally, the 'validateCartMutation' throws a 500 error, causing it to stop being called and thus freezing the cart. Is there any error handling in place? To recover from this error, currently, it's resolved by either proceeding to the checkout and clearing the cart or by navigating to 'Application' > 'IndexedDB' and performing a full reset. This issue seems to be intermittent.

In the screenshot provided below, the first item is from 'useProduct,' and the second one is from 'useCart.'
![Screenshot_2023-08-31_at_10 40 42](https://github.com/vtex/faststore/assets/102303809/11f5ed6e-fd7c-45cb-823f-55ad192876e7)

**Comment by beatrizmaselli** [comment]
PR https://github.com/vtex/faststore/pull/1983 was merged 

You can update the package to test it

**Comment by carollaginestrac4** [comment]
I'll test it and get back to you.

**Comment by emersonlaurentino** [comment]
1 week has passed, we will assume that everything is working correctly.
