### ISSUE TITLE
Carousel Navigation Controls Disappearing

### ISSUE THREAD

**Issue by fabsantandrea** [vtex/faststore#1986]
**Describe the bug**

The Carousel component navigation controls don't render when `scroll` and `infinite` mode are selected

**Expected behavior**

* Navigation controls shouldn't render only in the case they're selected not to appear.

**Current behavior**

This is the logic that decides wether to render the navigation controls or not:
![image](https://github.com/vtex/faststore/assets/88553996/46aa0cf8-c51b-4cbd-aa23-c82783cb1ef2)

 They only render when the items per page are less than the total number of product the carousel has. I think the problem is when the infinite mode is selected when the carousel variant is scroll (according to the documentation, they shouldn't be set at the same time). When you do this, for some reason, the carousel adds two more items (that are a copy of the already existent items)

![image](https://github.com/vtex/faststore/assets/88553996/823f5b27-4ff2-4839-b6cc-3666ef0b1706)

**Steps to reproduce**
A step-by-step on how to reproduce the bug behavior.

1.  I have 5 total items in the carousel.
2.  If I select 5 items per page, these are the results on the carousel: 7 items in infinite mode, and 5 with infinite mode disabled. I didn't see it happen with more than 10 items (minimum amount of items a carousel should have according to the documentation).

**Possible Solution**

 I think one solution would be disabling through code the infinite mode when the scroll variant is on. 

**Workspace**
All workspaces

**Comment by hellofanny** [comment]
Hi! Thanks for reporting this bug 🐞 . I'll take a look into it and get back to you.

**Comment by higaeduardo** [comment]
Thanks @hellofanny, let me know if you have a decision on this one!

**Comment by hellofanny** [comment]
Hey @fabsantandrea, I'm looking into this issue 🙈 
Can you tell me what layout you were trying to achieve, please?
It seems infinite mode is not behaving as expected too 😕 
Do you want the control to turn the navigation controls on/off. Is that what you are trying to do?

**Comment by fabsantandrea** [comment]
@hellofanny Yes, that would be great.

**Comment by hellofanny** [comment]
@fabsantandrea nice! 
When there are more items displayed in the carousel, we currently show the navigation controls only when hovering over the component. Are you looking to have continuous control, where the navigation controls are always displayed and not just when hovering? Or do you have other ideas for how you’d like to manage it?

**Comment by fabsantandrea** [comment]
@hellofanny that isn't something that **I'm** trying to accomplish in this issue, but it would be a nice feature.

**Comment by fabsantandrea** [comment]
@hellofanny @icazevedo forgive me. It would probably be the best to have full control of when the navigation controls appear, as Fanny mentioned.

**Comment by higaeduardo** [comment]
@fabsantandrea after our talk, can you confirm that these are the cases that you were having issues with?

1. When having 6 items on the carousel, and trying to show 4 on the front, the controls and pagination under the carousel wouldn’t appear
2. When having 5 items and showing 5 items, if we have an infinite mode on, the pagination shows controls and pagination under the carousel, even if the controls shouldn’t appear

**Comment by fabsantandrea** [comment]
@higaeduardo that is correct, yes.

**Comment by hellofanny** [comment]
Hello everyone!  We've worked on some enhancements to this component. Additionally, we've updated the documentation to provide a clearer understanding of how this [component](https://www.faststore.dev/components/molecules/carousel) functions.

Please try testing your use cases using the faststore/core `2.2.11` version. (_You might want to make some tweaks to the previously implemented code._)

A quick summary:
- `ItemsPerPage` will define the item's width declared inside (and the bullets quantity should appear according). 
- as mentioned [here](https://www.faststore.dev/components/molecules/carousel#infinite-scroll-mode), currently, the infinite mode is only supported under this props setup: itemsPerPage={1}, variant="slide" and infiniteMode={true}. You can try customizing the page to achieve the desired layout.
