### ISSUE TITLE
Headless CMS - Poor editing experience with draftjs-rich-text UI widget inside of array type

### ISSUE THREAD

**Issue by erinmorrissey-hearst** [vtex/faststore#2011]
**Describe the bug**
I created a new CMS section where the `draftjs-rich-text` UI widget is used inside of an **array** property type. When editing the content in the CMS where multiple items of the array property type are added, the DraftJS editing window stays at a fixed width and creates a poor editing experience:

![Screenshot 2023-09-06 at 1 06 03 PM](https://github.com/vtex/faststore/assets/130610878/3fc36f6a-be22-4299-8ef5-282d56aaf187)

**Expected behavior**
The DraftJS editing window should have a flexible width so it does not overlap with the other items and create a poor editing experience.

**Current behavior**
See above.

**Steps to reproduce**
The `sections.json` content that produced this issue:
```
{
    "name": "MembershipsAccordion",
    "schema": {
      "title": "Memberships - Accordion",
      "type": "object",
      "description": "FAQ content section in accordion form",
      "properties": {
        "sectionHeading": {
          "title": "Section Heading",
          "type": "string"
        },
        "accordionItems": {
          "title": "Accordion Items",
          "type": "array",
          "description": "Accordion item title and content",
          "items": {
            "title": "Item",
            "type": "object",
            "required": ["title", "content"],
            "properties": {
              "title": {
                "title": "Title",
                "type": "string"
              },
              "content": {
                "type": "string",
                "title": "Content",
                "widget": {
                  "ui:widget": "draftjs-rich-text"
                }
              }
            }
          }
        }
      }
    }
  }
  ```

1. Create a new CMS section using the object above.
2. In a CMS page, add that new section to the page.
3. Click "+ New Item" at least twice to get 3 items on the page
4. Observe that the DraftJS UI widget ("content" text block) is overlapping the others on the page.

**Possible Solution**
The DraftJS editing window should have a flexible width so it does not overlap with the other items and create a poor editing experience OR adding new items in a vertical column instead of in a row that doesn't wrap until 4 items exist may work as well.

**Workspace**
n/a

**Comment by vmlira2** [comment]
Hello, @erinmorrissey-hearst 

The issue has been addressed internally by the hCMS team. We'll share updates here as soon as we have something that solves the issue, ok?

Tks for reporting!

@FastStore team
