### ISSUE TITLE
Clicking on a product in the Cart Page of Checkout redirects to the legacy/IO website.

### ISSUE THREAD

**Issue by fabsantandrea** [vtex/faststore#2017]
**Describe the bug**
When you are in the cart page in checkout and click a product, you get redirected to the legacy/IO product page instead of the faststore page.

**Expected behavior**
When you are in the cart page in checkout and click a product, you should get redirected to the faststore product page.

**Steps to reproduce**
A step-by-step on how to reproduce the bug behavior.

1. Add a product to the cart
2. Go to cart page in checkout
3. Click on a product image

**Workspace**
All workspaces

**Additional context**
This behavior happens with the checkout already integrated with faststore

**Comment by emersonlaurentino** [comment]
Hey @fabsantandrea thanks for your report.

This behavior is expected, check this [documentation](https://www.faststore.dev/docs/go-live/3-integrating-the-the-vtex-login#step-1---adding-a-redirect-back-to-your-faststore-domain) that you'd fix it.
