### ISSUE TITLE
Product Grid component props are misplaced

### ISSUE THREAD

**Issue by fabsantandrea** [vtex/faststore#2061]
**Describe the bug**
- The "bordered" and "showDiscountBadge" props in ProductGrid are misplaced.

**Expected behavior**
- The "bordered" and "showDiscountBadge" props in ProductGrid should be in the correct place.

**Current behavior**
- Modifing the props through the hCMS doesn't actually work for it's purpose.

**Possible Solution**
- Switch the "bordered" and "showDiscountBadge" props in the ProductGrid component.

**Workspace**
Master workspace

**Additional context**

![image](https://github.com/vtex/faststore/assets/88553996/93638a33-c9fe-4c9d-9f66-5883b08b9156)

As you can see, you're passing the showDiscountBadge value as "Bordered" prop and the "bordered" value a to the "showDiscountBadge" prop.

Line of code: 

https://github.com/vtex/faststore/blob/e1489a02bc5e4de1aec3f9d60f77a3c4455cc22b/packages/core/src/components/product/ProductGrid/ProductGrid.tsx#L56C1-L56C1

**Comment by hellofanny** [comment]
Nice catch @fabsantandrea! 
Thanks for reporting it! I'll fix it! 👍

**Comment by hellofanny** [comment]
Fixed in `2.2.3` version 🥳 
Now, it should work as expected!
