### ISSUE TITLE
404 page does not reference error URL

### ISSUE THREAD

**Issue by batzlerg** [vtex/faststore#2064]
**Describe the bug**
The 404 page always references "This app could not find url /404" instead of the missing page

**Expected behavior**
1. user navigates to "/missing-page"
2. user lands on a 404 page with the text "This app could not find url /missing-page"

**Current behavior**
1. user navigates to "/missing-page"
2. user lands on a 404 page with the text "This app could not find url /404"

**Steps to reproduce**
A step-by-step on how to reproduce the bug behavior.

1. visit an undefined route in the app, such as [https://www.vtexfaststore.com/missing-page](https://www.vtexfaststore.com/missing-page)

**Possible Solution**
use `router.asPath` instead of `router.query.from`, or fix/implement whatever is supposed to populate `router.query.from` when the page redirects to 404.tsx

**Additional context**
<img width="412" alt="Screen Shot 2023-10-13 at 1 18 58 PM" src="https://github.com/vtex/faststore/assets/5392478/4d198271-eeac-4df9-a28f-d940c49099e9">
<img width="279" alt="Screen Shot 2023-10-13 at 1 24 02 PM" src="https://github.com/vtex/faststore/assets/5392478/6ae3dc85-978e-4473-ae54-40fa26929c0b">

**Comment by emersonlaurentino** [comment]
Hi @batzlerg good catch. This really needs to be adjusted.

Feel free to create a pull request with the correction.

**Comment by batzlerg** [comment]
opened a PR to address: https://github.com/vtex/faststore/pull/2083

**Comment by emersonlaurentino** [comment]
thanks
