### ISSUE TITLE
Remove duplicated h1 tag in search results page

### ISSUE THREAD

**Issue by vivaltech** [vtex/faststore#2093]
**Describe the bug**
There are two h1 tags in the same page

**Expected behavior**
Have only one h1 tag

**Current behavior**
The SROnly component is rendering a H1 tag instead of a span

**Steps to reproduce**

1. Navigate to the search results page
2. Two H1 will appear, one of them with the data-fs-sr-only attribute

**Possible Solution**
Remove the as="h1" attribute to render a span instead of a H1 tag

**Workspace**
Add a workspace where you tested the bug behavior.

**Additional context**
Here is the code that needs to be modified: https://github.com/vtex/faststore/blob/e1489a02bc5e4de1aec3f9d60f77a3c4455cc22b/packages/core/src/pages/s.tsx#L97

**Comment by hellofanny** [comment]
Nice catch! 🚀 
Fixed [here](https://github.com/vtex/faststore/pull/2096)
