### ISSUE TITLE
Addressing UI Rendering PLP: No Facets in Search Results

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#2131]
**Describe the bug**

Check the following[ search result](https://hearst.vtex.app/s?q=Flybird+Bundle%3A+Set+Of+Dumbbells+25+Lbs+%26+Weight+Bench+FB139&sort=score_desc&page=0)

Following the response, 38 results are received, and the presence of a Card skeleton persists because the search results lack facets . [This condition]  

We might not be getting the facets list for this search result, possibly due to configurations. However, it's important to still display the product list even if the facets are not available.

(https://github.com/vtex/faststore/blob/d766a3a32d882476d6234abd41ae7eb3818ea3b7/packages/core/src/components/ui/ProductGallery/ProductGallery.tsx#L95) in faststore core prevents the UI from rendering.

https://github.com/vtex/faststore/blob/d766a3a32d882476d6234abd41ae7eb3818ea3b7/packages/core/src/components/ui/ProductGallery/ProductGallery.tsx#L222

          {/* Render ALL products */}
          {hasFacets ? (
            <Suspense fallback={GalleryPageSkeleton}>
              {pages.map((page) => (
                <ProductGalleryPage
                  key={`gallery-page-${page}`}
                  page={page}
                  title={title}
                  productCard={productCard}
                  itemsPerPage={itemsPerPage}
                />
              ))}
            </Suspense>
          ) : (
            GalleryPageSkeleton
          )}

<img width="1388" alt="Screenshot 2023-11-29 at 10 09 09 AM" src="https://github.com/vtex/faststore/assets/137450920/64fe8dad-718c-4490-a634-90d21ce5e537">

**Comment by eduardoformiga** [comment]
Thank you for opening the issue, @victors1682 . 
We are going to double-check this logic with the team.
