### ISSUE TITLE
PLP search result is incorrect if there's no price on the SKU rendered 

### ISSUE THREAD

**Issue by Lucaspoladore** [vtex/faststore#2132]
**Describe the bug**
If we have offers from an external seller in a SKU that it's not the one being rendered, the PLP shows that the product is OOS, even though a couple other SKUs that might have offer. 

To see this happening right now, go to https://www.vtexfaststore.com/s?q=Apple+Magic+Mouse&sort=score_desc&page=0. You'll see the OOS product on the PLP 

![image](https://github.com/vtex/faststore/assets/72857548/13815b9b-03a1-4d40-9f07-7df632ff19b8)

The white mouse indeed has no stock https://www.vtexfaststore.com/apple-magic-mouse-99988212/p 

![image](https://github.com/vtex/faststore/assets/72857548/e704d662-64f0-46a7-b4d3-c26712293737)
![image](https://github.com/vtex/faststore/assets/72857548/a46e0b56-e533-4492-9c8b-bda3b8d552c2)
 
But the black mouse, has stock and price https://www.vtexfaststore.com/apple-magic-mouse-99988216/p

![image](https://github.com/vtex/faststore/assets/72857548/81bab2b9-8ed3-467b-83de-f3c6660cff56)
![image](https://github.com/vtex/faststore/assets/72857548/c8519e39-4611-441d-ad37-012bf2ce35fb)

Tests made: 
1) If the price is in the first SKU on the catalog (which I assume is the first one to be rendered) and the second product does not, then the PLP behaved properly 

<img width="1375" alt="image" src="https://github.com/vtex/faststore/assets/72857548/ee2f8a0b-c77c-4b44-b91d-bf4a46e06756">
<img width="1356" alt="image" src="https://github.com/vtex/faststore/assets/72857548/308e5439-347b-4879-8ec9-ac2f0a138722">
<img width="671" alt="image" src="https://github.com/vtex/faststore/assets/72857548/619f7fc3-4e51-4d48-8a7b-251df75756a6">
<img width="1263" alt="image" src="https://github.com/vtex/faststore/assets/72857548/d70281fd-3a53-46bd-82db-45cfaebf1300">
<img width="1203" alt="image" src="https://github.com/vtex/faststore/assets/72857548/b7c8156e-1cbb-4c7f-836d-e1c453d0b15c">

2) Second test was both not having stock, which renders OOS properly 
<img width="679" alt="image" src="https://github.com/vtex/faststore/assets/72857548/e9e91058-ddeb-4b84-874f-f280ce9fb673">
<img width="1207" alt="image" src="https://github.com/vtex/faststore/assets/72857548/f68cdc63-fd5a-4a8f-a9a4-afe4ee108aa8">
<img width="1261" alt="image" src="https://github.com/vtex/faststore/assets/72857548/c4d64245-dae5-4689-b46c-05e7dc743007">

3) But then, I did the test which is the actual problem that we are having. If I have 0 price / 0 inventory on the SKU rendered, then it shows OOS for me. Link: https://www.vtexfaststore.com/s?q=Apple+Magic+Mouse&sort=score_desc&page=0 

But if you go to the PDP, you see that there's actual price https://www.vtexfaststore.com/apple-magic-mouse-99988216/p 

**Expected behavior**
The expected behavior is in the 3rd scenario, we actually render the cost of the SKU that has stock. We would also redirect to the correct SKU, not the one OOS. 

**Steps to reproduce**
If you want to reproduce 100% what I did, just create an external seller (easy to do it with this template https://github.com/vtex-apps/external-seller-example) and change the prices for the SKUs that are rendered in any product that has more than 1 SKU + SKU Selector on the PDP.

**Comment by victors1682** [comment]
I tried to implement some logic to get the default seller on PLP, however, the query result coming from the GraphQL  `search`  does not contain the list of the offers/sellers. 

https://github.com/vtex/faststore/blob/d766a3a32d882476d6234abd41ae7eb3818ea3b7/packages/core/src/sdk/product/usePageProductsQuery.ts#L33C1-L61C2

Right now, the system only shows one offer, to avoid having too much information on the product list page. But, it's the job of the backend to choose the `defaultseller`.

**Comment by eduardoformiga** [comment]
addressed in 
- https://github.com/vtex/faststore/pull/2136
