### ISSUE TITLE
Add Babel in @vtex/gatsby-plugin-graphql automatically

### ISSUE THREAD

**Issue by tlgimenes** [vtex/faststore#214]
Currently, we need to add a .babelrc config file to the store's root folder. We should be able do add the babel config programatically via the plugin

**Comment by emersonlaurentino** [comment]
@tlgimenes this already works, doesn't it?

**Comment by tlgimenes** [comment]
No, we still need to use this because gatsby's babel plugins runs before our babel and removes all queries
