### ISSUE TITLE
Remove duplicated price as a list price if the product does not have list price

### ISSUE THREAD

**Issue by vivaltech** [vtex/faststore#2143]
**Describe the bug**
Regular price appears duplicated as a list price when the product does not have one

**Expected behavior**
When the product does not have any list price, it should only render the regular price

**Current behavior**
Right now, if the product does not have product list, renders the regular price as product list next to the regular one as a duplicated

**Steps to reproduce**
A step-by-step on how to reproduce the bug behavior.

1. ‘...’
2. ‘...’
3. ‘...’

**Possible Solution**
Add validation to prevent redenring the same price:

![image](https://github.com/vtex/faststore/assets/138598003/50831e83-c670-4ef9-a9a1-ced16c3c4bf8)

```
<section ref={ref} data-fs-search-product-item-content {...otherProps}>
      <p data-fs-search-product-item-title>{title}</p>
      {price?.value === price?.listPrice ? (
        <span data-fs-search-product-item-prices>
          <Price
            value={price?.value ? price.value : 0}
            formatter={price?.formatter}
            testId="price"
            data-value={price?.value}
            variant="spot"
            SRText="Price:"
          />
        </span>
      ) : (
        <span data-fs-search-product-item-prices>
          <Price
            value={price?.listPrice ? price.listPrice : 0}
            formatter={price?.formatter}
            testId="list-price"
            data-value={price?.listPrice}
            variant="listing"
            SRText="Original price:"
          />
          <Price
            value={price?.value ? price.value : 0}
            formatter={price?.formatter}
            testId="price"
            data-value={price?.value}
            variant="spot"
            SRText="Price:"
          />
        </span>
      )}
    </section>
```

Actual code: 
![image](https://github.com/vtex/faststore/assets/138598003/422f0ec6-3ab8-4500-8220-223ecbd0ccce)

Before:
![image](https://github.com/vtex/faststore/assets/138598003/dce81c0a-2040-48b9-a92e-3f6cf393ec22)

After:
![image](https://github.com/vtex/faststore/assets/138598003/c47555e7-52f2-4325-84db-988fbe66f9b7)

**Workspace**
Add a workspace where you tested the bug behavior.

**Additional context**
Add any other context, screenshots, or comments about the problem.

**Comment by hellofanny** [comment]
Thanks for reporting, we should fix it!  I've added this fix to the backlog. 🚀 
Feel free to create a pull request with the correction. 🌟

**Comment by hellofanny** [comment]
Hi! In the `@faststore/ui` version  2.2.63, we are introducing the `ProductPrice` to handle this issue.  For more details see https://github.com/vtex/faststore/pull/2179. 

Thanks 🌟
