### ISSUE TITLE
Landing Page canonical URL defaults to `storeUrl`

### ISSUE THREAD

**Issue by batzlerg** [vtex/faststore#2144]
**Describe the bug**
all VTEX Headless CMS pages of type "Landing Page" without a supplied `settings.seo.canonical` value default to the root domain in their canonical tag. this can lead to bad SEO outcomes.

**Expected behavior**
Landing Pages without a supplied value should use their actual addressable path from the CMS as the canonical `href` when the CMS value is unset

**Current behavior**
if the canonical value is left blank, [LandingPage.tsx](https://github.com/vtex/faststore/blob/b5f186103014bc51b4fbc5e1f3b5ef8b98a33b73/packages/core/src/components/templates/LandingPage/LandingPage.tsx#L44) uses the `storeConfig.storeUrl`, i.e. the `/` route

**Steps to reproduce**
1. create a Landing Page in the CMS and give it a path (e.g. `test-page`)
1. build a FastStore app against that storefront and navigate to the path
1. inspect the DOM and see that the canonical link is `<link rel="canonical" href="{storeConfig.storeUrl}">` instead of using the actual page URL

**Possible Solution**
update the logic in [LandingPage.tsx](https://github.com/vtex/faststore/blob/b5f186103014bc51b4fbc5e1f3b5ef8b98a33b73/packages/core/src/components/templates/LandingPage/LandingPage.tsx#L44) to take this into account. it should be fine to use the root domain + CMS configured path similar to [how the PDP does it currently](https://github.com/vtex/faststore/blob/42551deeabb190aa2f4efa0e0803fec593a997af/packages/core/src/pages/%5Bslug%5D/p.tsx#L232)

**Comment by jamesthethird** [comment]
Assigned. Reference: TCM-196

**Comment by jamesthethird** [comment]
@batzlerg the patch to Update default canonical URLs for landing pages has been merged, and is available in FastStore version 2.2.74 (in rollout). You should see these changes reflected later today.
