### ISSUE TITLE
Upgrade Your Twitter Logo

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#2169]
Update the social media Twitter logo to be able to select those from the CMS

https://starter.vtex.app/icons.svg

<img width="272" alt="Screenshot 2023-12-14 at 8 38 58 AM" src="https://github.com/vtex/faststore/assets/137450920/908af7cf-47e9-48a4-aba8-b717e04606f9">

<img width="269" alt="Screenshot 2023-12-14 at 8 39 42 AM" src="https://github.com/vtex/faststore/assets/137450920/16a0ae44-1f2a-455c-8330-07f29555d699">

**Comment by renatamottam** [comment]
Thanks for creating the issue, Victor. I'm working on this update and will add the PR here soon :)

**Comment by renatamottam** [comment]
The `@faststore/core` package version `2.2.59` was released with the update and it's ready to use :)
