### ISSUE TITLE
Check/update GTM ID validation

### ISSUE THREAD

**Issue by erinmorrissey-hearst** [vtex/faststore#2248]
**Describe the bug**
When generating a new FastStore app today via the Create Project page in the admin, I tried to enter our existing GTM ID (which has 8 characters after `GTM-`) and the form validation told me it was an invalid ID:

<img width="677" alt="Screenshot 2024-03-01 at 11 51 14 AM" src="https://github.com/vtex/faststore/assets/130610878/63c6d2bd-764e-4d32-a674-dd4684c39f3e">

**Expected behavior**
I should be able to enter a valid GTM ID so I don't have to manually change it in the repo post-app generation.

**Current behavior**
The field validation would not let me enter a valid ID.

**Steps to reproduce**
1. Start the process of generating a new FastStore app via the Create Project page in the admin
2. Try to enter a GTM ID with 8 characters (e.g. `GTM-12345678`)
3. Observe that the field throws a validation error

**Workspace**
n/a

**Comment by hellofanny** [comment]
Hello! Thanks for reporting it! This issue has been solved! ✅
