### ISSUE TITLE
PLP reload twice 

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#2304]
**Describe the bug**
PLP is loading the filters and products twice, which is causing delays in page loading. This issue began in FS v3 and is not present in our older legacy store in v2. The problem is affecting our monitoring process, as it takes longer load, and it's also impacting our LCP score.

**Steps to reproduce**
A step-by-step on how to reproduce the bug behavior.

1. Go directly to one category https://starter.vtex.app/office

**Additional context**

Faststore V3
![faststore-v3](https://github.com/vtex/faststore/assets/137450920/bb386b47-2dae-4333-b270-4e51835771eb)

![MH-v3](https://github.com/vtex/faststore/assets/137450920/11f2b8aa-f7f3-4f6c-b241-800a5e48ea08)

Faststore V2
![Faststore-v2](https://github.com/vtex/faststore/assets/137450920/889e55c7-72a3-41d1-b8ae-ac1d3802ffb7)

**Comment by eduardoformiga** [comment]
Thanks for the heads up on this issue, @victors1682 . We are addressing it with a task in our backlog to see the best way to just render it once but keep some needed attributes. As soon as we have updates, we will let you know.

**Comment by eduardoformiga** [comment]
@victors1682 update here: version [3.0.54](https://github.com/vtex/faststore/commit/21bd9cf63b6205f42b50bb744b67722ff794d256) was generated with the fix of this issue. We will close this issue, but please feel free to contact us.
- https://github.com/vtex/faststore/pull/2307

**Comment by victors1682** [comment]
@eduardoformiga @lariciamota  the issue is still happening take a look [MH](https://shop.menshealth.com/fitness---nutrition?productclusterids=162&fuzzy=0&operator=and&facets=productclusterids%2Cfuzzy%2Coperator&sort=score_desc&page=0)

also happening in [Faststore dev](https://starter.vtex.app/office?category-1=office&fuzzy=0&operator=and&facets=category-1%2Cfuzzy%2Coperator&sort=score_desc&page=0)
