### ISSUE TITLE
Application Crashes on Missing Pages Instead of Displaying 404 Error - Regression

### ISSUE THREAD

**Issue by victors1682** [vtex/faststore#2316]
**Describe the bug**
When the page is not found, the application breaks instead of displaying the 404 page.
Happening also: https://starter.vtex.app/test-page-no-found

**Expected behavior**
Show 404 page
<img width="851" alt="Screenshot 2024-05-15 at 9 55 10 AM" src="https://github.com/vtex/faststore/assets/137450920/71b7bff3-02a8-4b5d-917e-550c744de71f">

**Current behavior**
<img width="1127" alt="Screenshot 2024-05-15 at 9 56 02 AM" src="https://github.com/vtex/faststore/assets/137450920/481d1fe8-9c83-4d14-9f7a-7189cb79f595">

**Comment by lariciamota** [comment]
Thank you for reporting this!
We've just rolled back some changes that had caused this issue, it now seems to be working as expected
<img width="1435" alt="Screenshot 2024-06-13 at 11 42 50" src="https://github.com/vtex/faststore/assets/19983991/ced0319f-49a2-4fc5-8190-ec03707deea5">
