### ISSUE TITLE
New Price With Tax

### ISSUE THREAD

**Issue by evander-corebiz** [vtex/faststore#2363]
**Describe the bug**
I have a problem with the last commit (Add price with taxes feature).

**Expected behavior**
A price considering taxes.

**Current behavior**
An error in the function 'getLowPrice'.

**Steps to reproduce**
A step-by-step on how to reproduce the bug behavior.

1. Install the last version of the package.
2. Execute the query 'ClientManyProductsQuery'

**Possible Solution**

Enter a question mark to make the property optional.

**Workspace**
------NOT-------

**Additional context**

TypeError: Cannot read properties of undefined (reading 'Tax').

commit : https://github.com/vtex/faststore/commit/a965d3f837cf0a0872225d03895bd2b8a48802b1

![image](https://github.com/vtex/faststore/assets/84039510/4eee3c0a-c450-4f1e-9d2d-487fef0246dd)

![image](https://github.com/vtex/faststore/assets/84039510/c5b0114d-7291-4742-a3c5-ff052c7b019c)

**Comment by eduardoformiga** [comment]
Hey @evander-corebiz , thanks for opening this issue.
We have published a fix in the faststore core version 3.0.76. 

Can you double-check if it's working as expected with this version?

**Comment by evander-corebiz** [comment]
It seems to work well, thanks!
