### ISSUE TITLE
Hooks should be implemented in `use{HookName}.ts` files

### ISSUE THREAD

**Issue by kaisermann** [vtex/faststore#413]
Before #412, a bunch of files containing react hooks we not using the correct `vtex-react` preset, which means the `eslint-plugin-react-hooks` rules were not being applied. This is not only wrong but dangerous.

I suggest encouraging the practice of creating each hook in its own file, with its filename following the `use{HookName}.ts` pattern so it's not only easier to match them with our linter, but also to find a specific hook in the project.

**Comment by emersonlaurentino** [comment]
@kaisermann Should this pr still open?
