### ISSUE TITLE
Decouple store-ui from emotion

### ISSUE THREAD

**Issue by tlgimenes** [vtex/faststore#715]
We should decouple store-ui from emotion by removing all emotion related code from store-ui and moving them to the stores

**Comment by emersonlaurentino** [comment]
I'm working on this, and currently, we have only one component: Button. I will keep this issue updated with my works on new components.

**Comment by emersonlaurentino** [comment]
Button: #692

**Comment by emersonlaurentino** [comment]
🕐  Input: #696
