### ISSUE TITLE
Atoms

### ISSUE THREAD

**Issue by tlgimenes** [vtex/faststore#719]
implement different atoms in store ui. 

An atom is considered implemented when:
1. It has a .test.ts file alongside the component implementation
2. It has a .stories.ts file alongside the component implementation containing
   a. How to style it
   b. Basic doc on the purpose
   
A good inspiration on the atoms to create: [storefrontui](https://docs.storefrontui.io/?path=/story/welcome--page)

**Comment by emersonlaurentino** [comment]
To styling the components we want to use `data-attributes` like the [Reach UI](https://reach.tech/styling) components.

**Comment by icazevedo** [comment]
Here's a list of atoms I think we should have, beyond those already implemented:

# Atoms
### Bullets
Bullets should indicate where the user is located on a list, like in a slider, for example.

### Page View
Should arrange items side-by-side and allow for flexibility on content, size, and item dimensions. Every item is a page. We could use [slider-layout](https://github.com/vtex-apps/slider-layout) as inspiration, but we want it less opinionated, to have only the slide logic (no buttons or bullets), one page per item, and less IO bloated.

I like [Flutter's API](https://api.flutter.dev/flutter/widgets/PageView-class.html) a lot.

### Price
Should display prices with different attributes. ~~strikedthrough~~ or installments, for example.

I like [Flutter's API](https://api.flutter.dev/flutter/widgets/PageView-class.html) a lot.

### TextArea
We should offer a solution for TextArea similar to our current Input one.

### Label
I think we should offer a really simple label component just to help users with SEO and accessibility, but that's debatable.

### Ratings
Should display a list of user-chosen icons for positive and negative ratings. The amount of icons is customizable. _Should we support fraction ratings?_

### Product Specification
_Not sure how to provide this, but I feel we should. I think we should discuss this. How to atomize a table in a sensible way?_
