### ISSUE TITLE
Unreliable source VTEX

### ISSUE THREAD

**Issue by tlgimenes** [vtex/faststore#726]
When performing consecutive builds, we get different products being generated. The problem is that the VTEX Catalog API does not have a way of scraping all the products it has. To overcome this problem we perform an empty search and paginate over it. 

Problem: I think that this search is returning duplicated products and not returning all available products, making that some builds miss some products, thus not optimizing every page requested

**Comment by tlgimenes** [comment]
Nice find! I think this is indeed one of the problems @juliomoreira! Can you make a PR for this?
However we are still missing some products. I'm not sure that, by scanning the products using search API we get all products or if we still can miss one.

**Comment by juliomoreira** [comment]
The other ways that I'm aware of would all require authenticated requests to work ☹️.

**Comment by juliomoreira** [comment]
Are you comparing the results with the ones from admin? If so, the mismatch could be related to a number of reasons mainly because of user context which is absent in the admin but assumed in the public API and other configurations or attributes that play a role in displaying the product or not.

**Comment by tlgimenes** [comment]
> Are you comparing the results with the ones from admin? If so, the mismatch could be related to a number of reasons mainly because of user context which is absent in the admin but assumed in the public API and other configurations or attributes that play a role in displaying the product or not.

Not really. I'm getting this inconsistency when I do consecutive builds. Each build reports a different amount of products being fetched. I think this is because the search doesn't really scan over the database. We need such scan to make this feature to work

**Comment by juliomoreira** [comment]
Hi @tlgimenes  after a battery of tests here I was unable to find any inconsistencies with the Search API itself.

Testing with the pagination params fix indeed reduced the non-unique items.

However, I do have some interesting findings:

1. Improvements: We could read the `resources` header of the Search API and build pagination params from it to avoid fetching an unnecessary amount pages in cases where `maxNumPaths` exceeds this number.

2. Having categories/product paths in your staticPaths.json will result in `paths` containing duplicate items.

3. Edge case: you can end up with duplicate items in `paths` if you have a brand in which the computed path results to the same path of a category. Or you can have brands with the same name but different IDs. Same case with page

Idea: You could build categories and brands entirely with the results from the Search API, this would also ensure that category and brand pages have content reducing bundle size possibly and skip page type validation with Portal API for these paths maybe?
