### ISSUE TITLE
Validate build storage design

### ISSUE THREAD

**Issue by Jeymisson** [vtex/faststore#85]
Today we are creating one bucket per project to be built. Example storecomponents.store has a bucket where is saves the static assets gen per build in a structure git branch alike, e.g: `master/public`, `branch-1/public`, `branch-2/public`, etc...

Is this method ok? Are we gonna use S3, a S3 wrapper or other repo / filesystem method? This should be validated with @vtex/io-infra  and @reliability teams.

**Comment by tlgimenes** [comment]
we are using CAS
